# -*- coding: utf-8 -*-
"""Counter Expansion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VbBVpD1mISy2JbC6RdIjpE3rSUVP1tcR
"""



# main.py

import nibabel as nib
import numpy as np
import os
from skimage.filters import threshold_otsu
from scipy.ndimage import binary_dilation
import matplotlib.pyplot as plt
import shutil

def expand_mask_by_mm(binary_mask, voxel_spacing, expansion_mm=2):
    """
    Expands a binary mask outward by a specified number of millimeters.

    Args:
        binary_mask (2D np.array): The original binary mask.
        voxel_spacing (tuple): The physical size of each voxel (x, y).
        expansion_mm (float): Expansion distance in mm.

    Returns:
        expanded_mask (2D np.array): The dilated binary mask.
    """
    expand_pixels_x = int(np.round(expansion_mm / voxel_spacing[0]))
    expand_pixels_y = int(np.round(expansion_mm / voxel_spacing[1]))
    kernel = np.ones((2 * expand_pixels_y + 1, 2 * expand_pixels_x + 1))
    expanded_mask = binary_dilation(binary_mask, structure=kernel)
    return expanded_mask

# === Load image ===
nii_path = "/content/3702_left_knee.nii.gz"
nii = nib.load(nii_path)
data = nii.get_fdata()
print(data)
#extracting exactly 2mm from original pixel image
voxel_spacing = nii.header.get_zooms()[:2]

# === Create output directory to store the images ===
output_dir = "/content/expanded_output"
os.makedirs(output_dir, exist_ok=True)

# === Process each slice ===
for i in range(data.shape[2]):
    slice_img = data[:, :, i]

    if np.max(slice_img) == 0:
        print(f"Skipping blank slice {i}")
        continue

    # Normalize slice for saving
    norm_slice = (slice_img - np.min(slice_img)) / (np.ptp(slice_img) + 1e-8)

    # Otsu thresholding
    thresh = threshold_otsu(slice_img)
    binary_mask = slice_img > thresh

    # Expand mask by 2mm
    #voxel spacing is nothing but physical distance between x,y, and z directions.volume pixel

    expanded_mask = expand_mask_by_mm(binary_mask, voxel_spacing, expansion_mm=2)

    # Save original, mask, and expanded images in slice form
    plt.imsave(f"{output_dir}/slice_{i:03d}_original.png", norm_slice, cmap="gray")
    plt.imsave(f"{output_dir}/slice_{i:03d}_mask.png", binary_mask.astype(np.uint8), cmap="gray")
    plt.imsave(f"{output_dir}/slice_{i:03d}_expanded_mask.png", expanded_mask.astype(np.uint8), cmap="gray")

    print(f"Saved slice {i}")

# === Zip the output folder ===
zip_path = shutil.make_archive(output_dir, 'zip', output_dir)
print(f"\n✅ Zipped output saved at: {zip_path}")

# === Optional: Download ZIP if in Colab ===
try:
    from google.colab import files
    files.download(zip_path)
    print("📥 Download started.")
except ImportError:
    print("Not in Colab, download skipped.")