# -*- coding: utf-8 -*-
"""Randamised ADjustment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ax1fqrqQIPDisOCUFi4kRAZQeKm1VacT
"""

import os
import numpy as np
import nibabel as nib
import matplotlib.pyplot as plt
from skimage.filters import threshold_otsu
from scipy.ndimage import binary_dilation
import shutil

#This function is to convert mm into pixel,and create a elliptical structure kernal is created.

def expand_mask(mask, voxel_spacing, expansion_mm):
    exp_x = int(round(expansion_mm / voxel_spacing[0]))
    exp_y = int(round(expansion_mm / voxel_spacing[1]))
    kernel = np.ones((2 * exp_y + 1, 2 * exp_x + 1))
    return binary_dilation(mask, structure=kernel)

#This function through we can choose max expansion,random expantion value and new mask is created.

def generate_randomized_mask(original_mask, voxel_spacing, max_expansion_mm=2.0, random_mm_range=1.5):
    max_mask = expand_mask(original_mask, voxel_spacing, max_expansion_mm)

    rand_mm = np.random.uniform(0, random_mm_range)
    rand_mask = expand_mask(original_mask, voxel_spacing, rand_mm)

    final_mask = np.logical_and(rand_mask, max_mask)
    final_mask = np.logical_or(final_mask, original_mask)
    return final_mask.astype(np.uint8)

# === Paths and Setup  for output directory===
nii_path = "/content/3702_left_knee.nii.gz"  # Change this if needed
output_dir = "/content/randomized_output"
zip_path = f"{output_dir}.zip"
os.makedirs(output_dir, exist_ok=True)

# === Loading MRI data ===
nii = nib.load(nii_path)
data = nii.get_fdata()
print(data)
voxel_spacing = nii.header.get_zooms()[:2]
print("Loaded image shape:", data.shape)
print("Voxel spacing (mm):", voxel_spacing)

# === Parameters ===
max_expansion_mm = 2.0
random_mm_range = 1.5

# === Process Each Slice ===
for i in range(data.shape[2]):
    slice_img = data[:, :, i]

    if np.max(slice_img) == 0:
        print(f"Skipping blank slice {i}")
        continue

    norm_slice = (slice_img - np.min(slice_img)) / (np.ptp(slice_img) + 1e-8)

    # Otsu segmentation
    thresh = threshold_otsu(slice_img)
    binary_mask = slice_img > thresh

    # Expanded mask
    expanded_mask = expand_mask(binary_mask, voxel_spacing, max_expansion_mm)

    # Randomized mask between original and expanded
    randomized_mask = generate_randomized_mask(binary_mask, voxel_spacing, max_expansion_mm, random_mm_range)

    # Save images
    plt.imsave(f"{output_dir}/slice_{i:03d}_original.png", norm_slice, cmap="gray")
    plt.imsave(f"{output_dir}/slice_{i:03d}_mask.png", binary_mask.astype(np.uint8), cmap="gray")
    plt.imsave(f"{output_dir}/slice_{i:03d}_expanded.png", expanded_mask.astype(np.uint8), cmap="gray")
    plt.imsave(f"{output_dir}/slice_{i:03d}_randomized.png", randomized_mask, cmap="gray")

    print(f"✅ Saved slice {i}")

# === Zip Output ===
shutil.make_archive(output_dir, 'zip', output_dir)
print(f"\n📁 Output zipped at: {zip_path}")

# === Download from Google Colab ===
try:
    from google.colab import files
    files.download(zip_path)
    print("📥 Download started.")
except ImportError:
    print("Not in Colab, manual download required.")